sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t leegzhao/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leegzhao/react-test npm test

after_success:
  - docker build -t leegzhao/multi-client ./client
  - docker build -t leegzhao/multi-nginx ./nginx
  - docker build -t leegzhao/multi-server ./server
  - docker build -t leegzhao/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push leegzhao/multi-client
  - docker push leegzhao/multi-nginx
  - docker push leegzhao/multi-server
  - docker push leegzhao/multi-worker

# Deploy to AWS elasticbeanstalk. Need AWS account and create services
# including ebs, rds, elastic cache. See AWS configuration cheat sheet.
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
